# Generated by Django 4.1.3 on 2022-12-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('homework_sum', models.IntegerField(default=0)),
                ('homework_count', models.IntegerField(default=0)),
                ('difficulty_sum', models.IntegerField(default=0)),
                ('difficulty_count', models.IntegerField(default=0)),
            ],
        ),
    ]
