# Generated by Django 4.1.3 on 2022-12-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='essays',
        ),
        migrations.AddField(
            model_name='teacher',
            name='difficulty_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='homework_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='difficulty',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='homework',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
