# Generated by Django 4.1.3 on 2022-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='attendance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attendance_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='essays_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='essays_sum',
            field=models.IntegerField(default=0),
        ),
    ]
