# Generated by Django 4.1.3 on 2022-12-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_teacher_attendance_count_teacher_attendance_sum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='attendance_count',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='difficulty_count',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='essays_count',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='homework_count',
        ),
    ]
