# Generated by Django 4.1.3 on 2022-12-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_rename_attendance_count_teacher_votes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='attendance_sum',
            new_name='attendance',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='difficulty_sum',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='essays_sum',
            new_name='essays',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='homework_sum',
            new_name='homework',
        ),
    ]
